# Generated by Django 4.2.4 on 2023-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending'),
        ),
    ]
